### ISSUE TITLE
Scss compiler error: argument `$color` of `lighten($color, $amount)` must be a color

### ISSUE THREAD

**Issue by laurentpayot** [poetic/meteor-materialize-sass#1]
I'm trying to overwrite colors. 

Here's my colors.scss file:

<pre>
/*** Colors ***/
$primary-color: color("orange", "lighten-2") !default;
$secondary-color: color("deep-orange", "lighten-1") !default;
$success-color: color("green", "base") !default;
$error-color: color("red", "base") !default;
$link-color: color("light-blue", "darken-1") !default;
</pre>

Here's my index.scss file:

<pre>
// If you want to override colors, you can import color variables before materialize.scss
@import "client/stylesheets/colors.scss";
@import ".meteor/local/build/programs/server/assets/packages/yang2007chun_materialize-scss/bower_components/materialize/sass/materialize.scss";
</pre>

All I get is Scss compiler error:

<pre>
=> Errors prevented startup:                  
   
   While building the application:
   /home/laurent/myapp/meteor/.meteor/local/build/programs/server/assets/packages/yang2007chun_materialize-scss/bower_components/materialize/sass/components/_variables.scss:3:23: Scss compiler error:
   argument `$color` of `lighten($color, $amount)` must be a color
   
   Backtrace:
   .meteor/local/build/programs/server/assets/packages/yang2007chun_materialize-scss/bower_components/materialize/sass/components/_variables.scss:3, in function `lighten`
   .meteor/local/build/programs/server/assets/packages/yang2007chun_materialize-scss/bower_components/materialize/sass/components/_variables.scss:3
   
   
=> Your application has errors. Waiting for file change.

</pre>

**Comment by Chun-Yang** [comment]
lighten($color, $amount)  is a function provided by materialize. The problem is materialize is not loaded yet when you call this function. You can use a regular color like 'red'. 

If you want to use there function, you can lookup their color palette  http://materializecss.com/color.html

**Comment by laurentpayot** [comment]
Thanks for your quick reply. I ended up directly using hexadecimal values from their palette. It did the trick.

Nice package :+1:

**Comment by nicolaslopezj** [comment]
You can do this

**client/styles/main.scss**

``` scss
@import ".meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/components/_color.scss";
@import "client/styles/variables.scss";
@import ".meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss";
```

**client/styles/variables.scss**

``` scss
$primary-color: color("blue", "lighten-2");
```

**Comment by laurentpayot** [comment]
Thanks @nicolaslopezj , I'll try this.

**Comment by Nick-vr** [comment]
This doesn't work anymore?

**Comment by Chun-Yang** [comment]
@Naiki This repo is archived, can you check this new package https://github.com/poetic/meteor-materialize-scss/  ? If you still have this problem, please file a issue there. Thank you!

**Comment by dmchandru** [comment]
Thank you so much @nicolaslopezj . It's working.... 👍

**Comment by natank** [comment]
In Materialize 1.0.0 do this:
```
// import Materialize colors
@import 'materialize-css/sass/components/_color-variables.scss';
@import 'materialize-css/sass/components/_color-classes.scss';

// Override Materialize variables
@import './_variables';

// Materialize Styles
@import 'materialize-css/sass/materialize.scss';
```
