### ISSUE TITLE
New materialize release 0.97.1

### ISSUE THREAD

**Issue by serkandurusoy** [poetic/meteor-materialize-sass#10]
Hello guys,

Materialcss released 0.97.1 today, but unfortunately it [breaks meteor](https://github.com/Dogfalo/materialize/issues/2037) due to packaging error.

Would you be terribly kind to update your version to our rescue so that we can leave behind our long standing material woes :)

**Comment by Chun-Yang** [comment]
At this point we already did a lot of customized stuff. It will take some time to do this update. Do you mind helping with this update? @serkandurusoy  I may do this after a while since it is not  in high priority.

**Comment by serkandurusoy** [comment]
I see, I'm merely a copy-paste guy when it comes to CSS, so I doubt I can be of any help :(

**Comment by sean-stanley** [comment]
+1
What sort of work is required to update this package to 0.97.1? Some of the proposed fixes involve simply using the non-minified version of materialize js in version 0.97.1 That doesn't sound too hard.

**Comment by Chun-Yang** [comment]
1. bower update (easy)
2. use new js file (easy)
3. preserve icons, make sure they are imported (take time)
4. make sure the bugfix we did in materialize.js is preserved. Please refer to https://github.com/poetic/meteor-materialize-sass/commit/d8c9e2ae7fba9bf09c12a127c0e05f25a9f1ac0c (take more time)

Keep in mind for every update, I have to go through 1-4 which is kind of painful.
I may update this project when I have time. Or maybe when the bugs are resolved in their repo. Or when they have a more stable release.

**Comment by TomFreudenberg** [comment]
For some curios effects due to materialize see also: https://github.com/Dogfalo/materialize/issues/2120 and https://github.com/Dogfalo/materialize/issues/2134

**Comment by aykutyaman** [comment]
+1 for the update

**Comment by swarshah** [comment]
I have updated Materialize to 0.97.3 in my fork https://github.com/SwarShah/meteor-materialize-sass and it seems it's working fine for me as a local package, but I'm not sure whether I did everything correct or not. Along with that, I have preserved this d8c9e2a changes. Try it and let me know if something is not correct. :)

**Comment by Chun-Yang** [comment]
Thank you @SwarShah , I will take some time to check your change. :+1:

**Comment by Chun-Yang** [comment]
@SwarShah I rewrote the whole package in https://github.com/poetic/meteor-materialize-scss and archived this repo. Thank you for your help. I am really sorry I wasted your PR.

Please try to use the new package. It should be more maintainable.

**Comment by swarshah** [comment]
@Chun-Yang It's ok. Yes you are right now the package looks great and more maintainable.
Thanks.
