### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by boustanihani** [poetic/meteor-materialize-sass#13]
Hi, I am getting this error after upgrading to 1.3.2, I am using Ubuntu 14.04 (64bit) => 

```
=> Errors while upgrading packages

While checking for poetic:materialize-scss@1.3.2:
error: No compatible binary build found for this package.
Contact the package author and ask them to publish it for your platform.
```

**Comment by Chun-Yang** [comment]
The reason is that my internet connection is bad. I can not upload a build successfully. 

For now, please download the whole repo and put it in packages folder, I will publish the project later.

Sorry about the inconvenience.

**Comment by Chun-Yang** [comment]
Or you can use 1.2.10 which is for meteor@1.1.x

**Comment by boustanihani** [comment]
ah okay cool, great work :+1:

**Comment by Chun-Yang** [comment]
Try remove and add the package again. I just uploaded the package.
