### ISSUE TITLE
icons for sub-buttons on floating button menu is offset in safari and mobile safari

### ISSUE THREAD

**Issue by strataga** [poetic/meteor-materialize-sass#14]
I am using v1.2.3. When I test in the emulator for mobile safari and normal desktop safari, the icons for the sub-buttons on a floating button menu is offset.

<img width="64" alt="screen shot 2015-10-02 at 3 41 48 am" src="https://cloud.githubusercontent.com/assets/10903600/10242622/c0abd7f0-68b7-11e5-917c-679dc8c2537f.png">

Looks OK for desktop Chrome and Firefox.

Sample code:

```
<div class="fixed-action-btn active" style="bottom: 45px; right: 24px;">
     <a class="btn-floating btn-large red">
      <i class="mdi-content-add"></i>
   </a>
  <ul>
       <li>
           <a href="#" class="btn-floating red" title="New Application" style="transform: scaleY(1) scaleX(1) translateY(0px); opacity: 1;">
                <i class="material-icons">note_add</i>
           </a>
      </li>
   ....
  </ul>
</div>
```

**Comment by Chun-Yang** [comment]
This is a problem of materializecss. You can start a issue there. Thank you!

**Comment by strataga** [comment]
Ah ok thanks!
