### ISSUE TITLE
Version 1.3.4 breaks again

### ISSUE THREAD

**Issue by TomFreudenberg** [poetic/meteor-materialize-sass#16]
Hi, after updating to release 1.3.4 can't run meteor

<pre>
   While processing files with fourseven:scss (for target web.browser):
   /packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss: Scss compiler error: File to import:
   {poetic:materialize-scss}/bower_components/materialize/sass/components/chips not found. Import origin:
   /packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss

   /client/index.scss: Scss compiler error: File to import: {poetic:materialize-scss}/bower_components/materialize/sass/components/chips not found. Import origin:
   /client/index.scss
</pre>

Haven't yet the time to check but going back to 1.3.3 made me running successfull

**Comment by TomFreudenberg** [comment]
Ok, got it. You missed to add the file `_chips.scss` to the packages list.

https://github.com/poetic/meteor-materialize-sass/blob/master/package.js#L63-L64

I have not made a PR – sure its a quick for you.

Cheers
Tom

**Comment by Chun-Yang** [comment]
I made a mistake. I should not have merged a PR since we are still on 0.97.0.

Thank you very much!
