### ISSUE TITLE
Please use sub-module 

### ISSUE THREAD

**Issue by dcworldwide** [poetic/meteor-materialize-sass#2]
Please use a sub-module to ensure this package has the latest code from materialise master

**Comment by Chun-Yang** [comment]
Hey @dcworldwide, I really appreciate your suggetion.

Even though I use submodule, I still need to manuelly update the package using git pull.

Right now I am using bower. There are several benefit
1. I can check the version of materialize very easily(submodule gives you a hash)
2. If other peolple want to fork it and make an update, every will know the version of materialize. 

submodule and bower are just two ways to manage dependencies. If you have better reasons for submodule please let me know.
