### ISSUE TITLE
Waves effect doesn't return to default color

### ISSUE THREAD

**Issue by fabyeah** [poetic/meteor-materialize-sass#3]
Adding the package breaks the waves effect. It doesn' return to the intial color and additionally clicking a button several times stacks the effect. 

I tried not importing the waves.scss in materialize.scss, but that didn't fix the problem entirely.

I added all the scss files directly to my project and this works for now.

**Comment by Chun-Yang** [comment]
did you uninstall the materialize:materialize package?

**Comment by fabyeah** [comment]
Ah ok, I didn't do that. I thought I still needed the materialize package for the javascript. I didn't realize your package contains everything materialize:materialize contains, not just the sass files. Thank you.
