### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by bbshopadmin** [poetic/meteor-materialize-sass#4]
I installed the package as described in the readme, but can't see the icons. They don't get loaded or something.

folder/files exists:
`.meteor/local/build/programs/web.browser/packages/yang2007chun_materialize-scss/bower_components/materialize/font/material-design-icons`

**Comment by Chun-Yang** [comment]
Can you show me your code for the icon tag?

**Comment by juzerali** [comment]
Material-Design-Icon fonts need to be included for icons to work. But I can see only Roboto-Regular being included.

**Comment by bbshopadmin** [comment]
I tried this materialze docs example
`<i class="material-icons">add</i>`

**Comment by bbshopadmin** [comment]
I didn't include
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by juzerali** [comment]
Yeah, I just checked. Those icons are no more added by default in
materialize library. You have got to load it from google.

Regards,
Juzer Ali
http://about.me/juzerali

**Comment by Chun-Yang** [comment]
Materialize updated to 0.97.0. They now require user to include the icon stylesheet:
http://materializecss.com/icons.html

```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

This package now only support 0.96.1. You can use icon like this without including the stylesheet:

```
<i class="mdi-navigation-menu"></i>
```

**Comment by bbshopadmin** [comment]
Thank you two.

Will you update to v0.97.0 soon? For offline (e. g. mobile app) usage it would be great to have the choice between that googleapis link and self included fonts/icons.

**Comment by Chun-Yang** [comment]
@bbshopadmin Just upgrade, I did not include the icon-font since it is materialize's choice.
