### ISSUE TITLE
New Material Icons - Self Hosting

### ISSUE THREAD

**Issue by TomFreudenberg** [poetic/meteor-materialize-sass#5]
Hi, first of all thanks for providing that package

I have two questions:
1. will you add support for the self hosted Material-Icons fonts instead using the google web fonts? see https://google.github.io/material-design-icons/  
2. why are there still the Material-Design-Icons font files and rules added? Aren't them outdated and not in use anymore?

Thanks for short feedback

Tom

**Comment by Chun-Yang** [comment]
Hey @TomFreudenberg , I am glad that you use this package.
1. About your first question, I think it is a GREAT idea and I want to implement this. But right now I am little busy ( I maybe will check this next weekend ). If you could contribute, that would be AWESOME! I WILL review and accept your PR(In < 1 day).
2. About your second question. If you check the package.json, you will find that only roboto font is added and Material-Design-Icons is not added. The Material-Design-Icons are in the bower_components folder, but again it is not included in the package.json. Therefore it is not included in your meteor project. Am I missing any thing?

P.S. If you like this package, please star it and spread the :heart:

**Comment by TomFreudenberg** [comment]
Hi @Chun-Yang 

yes I am doing a PR today - already be prepared for that. Question is still about the deprecated "Material-Design-Icons". In current release of materializecss they are still available but not described anymore. That means, that also your meteor package should have to include the Material-Design-Icons font as long as they drop them out.

So for having most compatibilty we have to choose if 

a. I already drop out everything of Material-Design-Icons

b. or still let everything untouched from Material-Design-Icons as long if they drop it

and implement the new Material-Icons in parallel.

Any personal suggestion?

(See also https://github.com/Dogfalo/materialize/issues/1619)

**Comment by TomFreudenberg** [comment]
Hi @Chun-Yang 

I created an issue at the materializecss project to check wether it isn't the better way to implement the "self hosted Material-Icons font" directly on that side.

I am waiting for their reply before start the implemenation

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Just used the new package from atmosphere :-) works great!

Thanks for fast apply and support!

Cheers
Tom

**Comment by TomFreudenberg** [comment]
@Chun-Yang - I suggest to add an additional comment to README.md

> If you update and still miss the icons font, people should run `meteor reset` to get a fresh build.

I had this minutes ago on another project.

**Comment by TomFreudenberg** [comment]
Hi @Chun-Yang 

have you see the updated issue from materializecss project at

https://github.com/Dogfalo/materialize/issues/1619

It seems that they want to handle this Icon font different from the other fonts. Cannot get their point, maybe they send a reply to my last question.

Would you continue to deliver the font locally even if they won't include it in materializecss directly? I guess for this meteor package it is still valid and very handy.

Thanks for feedback
Tom

**Comment by Chun-Yang** [comment]
I guess they want to decouple icons from their project and let users choose to add it or not. It make sense since users can opt out and reduce the load time. 

In meteor, some times the app is an mobile app and we need the font to be avaliable locally. 

So I agree that we should include the iocns in our package.

**Comment by TomFreudenberg** [comment]
Great, thanks for your feedback. If case you need maintenance support just route an issue.
