### ISSUE TITLE
Sass maps?

### ISSUE THREAD

**Issue by jshimko** [poetic/meteor-materialize-sass#7]
Looks like there's an issue with `fourseven:scss` not compiling [sass maps](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps).  I get the following error when I try to import the scss...

``` bash
While building the application:
client/scss/main.scss: Scss compiler error: undefined

.meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/components/color:11:
Error: error reading values after "lighten-5"
```

...which is [this line](https://github.com/Dogfalo/materialize/blob/master/sass/components/_color.scss#L11) in the source.

Sass maps support with node-sass seems a little unclear.  Is there a way around this issue?

**Comment by Chun-Yang** [comment]
I think the problem is that node sass does not support specific syntax for sass map. If that is the case, you would need to turn off the sass map unfortunately.

**Comment by jshimko** [comment]
Ok.  So that said, it looks like this package doesn't actually work when used as described in the readme, right?

**Comment by Chun-Yang** [comment]
https://github.com/fourseven/meteor-scss#sourcemaps-since-200_1

It works when you turn off source map.

**Comment by jshimko** [comment]
Oh, gotcha.  Sorry, didn't see that setting.

**Comment by jshimko** [comment]
Oh wait, that link is talking about disabling [source maps](http://thesassway.com/intermediate/using-source-maps-with-sass), not [_sass_ maps](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps).  Those are two different things.  

Do you have this package successfully compiling in a Meteor app?  Materialize depends on those particular maps to define color variables via mixins, so I'm not sure how skipping that could ever possibly work.  Am I missing a detail somewhere?

**Comment by Chun-Yang** [comment]
Oh I see.  
1 I am using this package in my app now.
2 I will get back to this later
3 Can you give me a full error message stack and your package versions?

Thank you

**Comment by jshimko** [comment]
Oh wow.  Just discovered a really odd error.  Unless I specifically define the version constraint for the `fourseven:scss` package, Meteor keeps falling back to a really old version.  I only have it as a dependency in one place and the specific version isn't defined, so I'm not sure why it's doing that.  Even running `meteor update` or `meteor update fourseven:scss` won't override it.  But hard coding `fourseven:scss@3.2.0` forced the update and cleared up the error.

What the hell, package system??  Not sure how that even happens.

**Comment by jshimko** [comment]
Thanks for the quick replies!  (and the questions that led me solve my own problem!)
