### ISSUE TITLE
icon align in floating circular button

### ISSUE THREAD

**Issue by wastemobile** [poetic/meteor-materialize-sass#8]
Default icon in floating circular action button unable to align:

![icon](https://cloud.githubusercontent.com/assets/451223/9188496/64f36b88-400f-11e5-88c8-317d2a053f08.png)

``` html
<a class="btn-floating btn-large red">
    <i class="material-icons">build</i>
</a>
```

I fix with this amendment, but are not sure whether it is the best solution.

```
.material-icons {
  min-height: 1em;
  height: inherit;
}
```

![icon2](https://cloud.githubusercontent.com/assets/451223/9188565/5561ae40-4010-11e5-9f10-938fecee0a11.png)

**Comment by Chun-Yang** [comment]
I can not reproduce this behavior. It may come from your custom css. 

Thank you for reporting this!

**Comment by wastemobile** [comment]
Sorry, just found Safari seems to be the problem. But Safari browse original materialize site show align normally, it's weird. Thanks anyway.

![safari](https://cloud.githubusercontent.com/assets/451223/9189427/e2b84bfa-401a-11e5-81cd-748c58ea0e77.png)
