### ISSUE TITLE
Question: Custom CSS loading order...

### ISSUE THREAD

**Issue by boustanihani** [poetic/meteor-materialize-sass#9]
I had some custom CSS rules, which I wanted to get loaded after materialize. After using this package they are getting loaded before and thus getting overriden by materialize.

What do I need to do so my custom CSS rules are placed after the materialize ones?

Thanks in advance...

**Comment by Chun-Yang** [comment]
Please read more at https://github.com/fourseven/meteor-scss#controlling-load-order-since-200-beta_3 .
1. You need to change .css to .scss file. Since scss is a compatible with css, you only need to change the extension name. 
2. You need to add your .scss file into index.scss file like this:

```

@import ".meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss";

@import "client/stylesheets/utils.scss";
@import "client/stylesheets/base.scss";
...
```

**Comment by boustanihani** [comment]
Thanks for the quick response :bowtie:
